services:
  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=J0AhMXX4H0QBrRr8R1U098y8aA1@
    ports:
      - "1433:1433"
    volumes:
      - sqlvolume:/var/opt/mssql

  db-init:
    build:
      context: .
      dockerfile: Dockerfile.init
    depends_on:
      - db

  jupyter:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    environment:
      - DB_SERVER=db
      - DB_NAME=ServicioCiudadanoDW
      - DB_USER=SA
      - DB_PASSWORD=J0AhMXX4H0QBrRr8R1U098y8aA1@
      - DB_DRIVER=ODBC Driver 18 for SQL Server
      - DB_TRUSTED=no
    depends_on:
      - db
      - db-init

volumes:
  sqlvolume:
