FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

# Install sqlcmd
RUN apt-get update && apt-get install -y curl gnupg2 \
    && curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg \
    && curl -fsSL https://packages.microsoft.com/config/debian/12/prod.list > /etc/apt/sources.list.d/mssql-release.list \
    && apt-get update \
    && ACCEPT_EULA=Y apt-get install -y mssql-tools18 \
    && apt-get clean

ENV PATH="$PATH:/opt/mssql-tools18/bin"
COPY . .
CMD ["bash", "init-db.sh"]
